### ISSUE TITLE
Add RNA central

### ISSUE THREAD

**Issue by cmungall** [geneontology/neo#1]
RNAC provides various downloads. The GFF seems most complete. However, this doesn't seem to include MOD mappings. Where do these come from.

**Comment by cmungall** [comment]
Dependent on https://github.com/RNAcentral/rnacentral-webcode/issues/42

**Comment by cmungall** [comment]
Update: test file provided is sufficient, just need to add to pipeline

**Comment by cmungall** [comment]
We would prefer to use GPI, see https://github.com/RNAcentral/rnacentral-webcode/issues/58

**Comment by cmungall** [comment]
Note: currently we're getting RNA IDs via GPIs (which come originally from RNAC). We may still want to bring more of RNAC in directly, but this is not urgent (and blocked on the above ticket)

**Comment by cmungall** [comment]
Note to self: RNCA GPI gzip is 200m gzipped, 2.5gb uncompressed

**Comment by pgaudet** [comment]
can this be closed?
