### ISSUE TITLE
RNAcentral IDs incorrectly use OBO PURL namespace

### ISSUE THREAD

**Issue by balhoff** [geneontology/neo#100]
I believe this is the cause of ShEx violations caused by missing root types, noted here:
https://github.com/geneontology/neo/issues/99
https://github.com/geneontology/minerva/issues/481

**Comment by kltm** [comment]
@balhoff Regarding https://github.com/geneontology/neo/pull/101
What is a positive or negative test we can use to prove that this worked when we go for our next update?

**Comment by balhoff** [comment]
@kltm after this change, NEO should no longer contain a term `http://purl.obolibrary.org/obo/RNAcentral#_URS000229B2C9_9606`. It should now contain a term `http://rnacentral.org/rna/URS000229B2C9_9606`.

**Comment by kltm** [comment]
Some browsing on early products seems to essentially confirm that the change is in place:
```bash
$ zgrep -a "URS000229B2C9_9606" blazegraph-go-lego-reacto-neo.jnl.gz | grep -a -c purl
0
$ zgrep -a "URS000229B2C9_9606" blazegraph-go-lego-reacto-neo.jnl.gz | grep -a -c rnacentral
1
```

**Comment by kltm** [comment]
Will close once in production so that other issues know to revisit.

**Comment by kltm** [comment]
This should be out.
