### ISSUE TITLE
Some IDs we expect are not found in Noctua

### ISSUE THREAD

**Issue by pgaudet** [geneontology/neo#103]
For example: P06019

This is a Swiss-Prot reviewed entry, but it doesn't seem to be in NEO?

**Comment by kltm** [comment]
@pgaudet It does indeed seem not to be in the final `neo.obo`:
```
grep -c P06019 neo.obo
0
```
Okay, so let's peek at what's happening inside the "build" process. It exists in the upstream file:
```
grep -c P06019 uniprot_reviewed.gpi.tmp
1
```
It does _not_ exist in the filtered version:
```
grep -c P06019 filtered_uniprot_reviewed.gpi.tmp 
0
```
Okay, so why is it getting filtered? Looking at the line in the upstream source:
```
UniProtKB       P06019  repc    Repressor protein c     repc|c|Mup01    protein taxon:10677             RefSeq:NP_050605.1|EMBL:AF083977        db_subset=Swiss-Prot|taxon_name=Escherichia phage Mu|proteome=gcrpCan
```
Looking through the code of the simple filter, it seems I coded in a regexp that was a little too aggressive, meaning that in some cases, taxon IDs that started with a "1" would get unnecessarily filtered. I've applied a fix that I believe will work.

Assuming it gets through the testing (starting now), we can either wait until the outage in two weeks to apply the change or coordinate an earlier time with @vanaukenk .

**Comment by kltm** [comment]
Testing locally, it looks like we've bumped up the number of entities to 1625034 and we now have the ones that were missing.
```
$ grep P06019 neo.obo 
id: UniProtKB:P06019
```
With no further action, this will go into production next week.

**Comment by pgaudet** [comment]
Sounds good, thanks for debugging this. 

Pascale

**Comment by pgaudet** [comment]
Next step: check at the next Noctua release next Friday May 27th

**Comment by pgaudet** [comment]
I can now find P06019

Thanks!
