### ISSUE TITLE
Xenbase identifiers are not correct getting labels (in NEO?)

### ISSUE THREAD

**Issue by kltm** [geneontology/neo#109]
This issue seems to have recurred. It only seems to affect some genes and in some cases both gene symbols and URIs are being shown in the same model.
![image](https://user-images.githubusercontent.com/23216004/181033547-c0e569ee-9a77-4d06-a3dc-60464d19d3b2.png)

The issue may be somewhat different as currently the gene symbols are not showing up in the Noctua lookup.
![image](https://user-images.githubusercontent.com/23216004/181035658-587a64af-e724-40af-aed9-a4f2949ee545.png)

_Originally posted by @malcolmfisher103 in https://github.com/geneontology/noctua/issues/706#issuecomment-1195572742_

**Comment by kltm** [comment]
@malcolmfisher103, let's go through the NEO update cycle this Thursday and if the problem is still occurring we can start running it down.

**Comment by kltm** [comment]
Noting that this is persisting after update. Also noting that these are indeed the given symbols:
http://noctua-amigo.berkeleybop.org/amigo/term/Xenbase:XB-GENE-17329976
http://noctua-amigo.berkeleybop.org/amigo/term/Xenbase:XB-GENE-17345783

**Comment by kltm** [comment]
@malcolmfisher103 This seems to be an issue with the upstream GPI in the metadata: https://ftp.xenbase.org/pub/GenePageReports/xenbase.gpi.gz
The lines for these identifiers do not seem to contain symbols, so the symbol falls back to the identifier.

**Comment by malcolmfisher103** [comment]
Thanks for chasing this up @kltm, I was just doing the same thing. There seems to be an issue with the gpi production script that has lead some genes haveing an empty column for the gene symbol which seems to lead to the XB-GENE-ID being assigned as the symbol

**Comment by kltm** [comment]
Cheers!
