### ISSUE TITLE
Add FB Developmental and Anatomy Ontology

### ISSUE THREAD

**Issue by hattrill** [geneontology/neo#117]
Adding this here (not sure if it is better on Neo tracker?)

Please add two fly ontologies to NEO:

FlyBase Developmental Ontology (FBdv, http://obofoundry.org/ontology/fbdv)
Latest version: http://purl.obolibrary.org/obo/fbdv.owl

and 

FlyBase Anatomy Ontology (FBbt; http://obofoundry.org/ontology/fbbt)
Latest version: http://purl.obolibrary.org/obo/fbbt.owl

**Comment by kltm** [comment]
@balhoff I guess the two things to do here are to either just add them separately to the GOlr load (https://github.com/geneontology/pipeline/pull/344) or to add them to `go-lego.owl`. Any thoughts one way or another?

**Comment by balhoff** [comment]
I think we should add to go-lego/go-amigo; otherwise we could run into the problems we had before with the reasoner and direct loading into AmiGO.

**Comment by kltm** [comment]
@balhoff Hm. How many terms are we talking about here? I'd be guessing, looking at the non-GO ontologies we already load (https://amigo.geneontology.org/amigo/search/ontology), that it would be unlikely to make a huge change.
If so, could you close the PR out in favor of changes to the ontology build (and link that here)?

**Comment by balhoff** [comment]
Pull request over here: https://github.com/geneontology/go-ontology/pull/26523.

**Comment by kltm** [comment]
We don't quite have a state for this, but I would expect this to propagate out by the next release or so.

**Comment by vanaukenk** [comment]
@kltm @balhoff 

Just double-checking about this work before tomorrow's maintenance outage.  Will this require a successful snapshot release to percolate to production Noctua?

**Comment by balhoff** [comment]
Luckily I see FBbt in yesterday's successful snapshot. :-)

**Comment by hattrill** [comment]
All seems good to me wrt ontologies. So I will close this.

@vanaukenk Might need a bit of help with interface, but we can go over this in training after Christmas. 

Thanks

**Comment by pgaudet** [comment]
Added  database: FBdv to [dbxref.yaml file](https://github.com/geneontology/go-site/blob/842184393e7b1dfbef4f85bf5402ff147836dbcf/metadata/db-xrefs.yaml)

 database: FBdv
  name: Drosophila development
  rdf_uri_prefix: http://purl.obolibrary.org/obo/FBdv_
  generic_urls:
    - http://flybase.org/
  entity_types:
    - type_name: life cycle stage
      type_id: UBERON:0000105
      id_syntax: '[0-9]{8}'
      url_syntax: http://flybase.org/cgi-bin/fbcvq.html?query=FBdv:[example_id]
      example_id: FBdv:00007012
      example_url: http://flybase.org/cgi-bin/fbcvq.html?query=FBdv:00007012


PR is here: https://github.com/geneontology/go-site/pull/2292

**Comment by kltm** [comment]
Since closing, there have been two more PRs. Is this now completed?
