### ISSUE TITLE
RNAC entries missing for human

### ISSUE THREAD

**Issue by cmungall** [geneontology/neo#15]
noticed by @rachhuntley

**Comment by rachhuntley** [comment]
We annotate to multiple species, not just human, so we'd need the identifiers for other species too.
GOA provides the GOC with individual gpi files for RNAs from each species, however RNAcentral has a gpi file that includes everything;
ftp://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/gpi/rnacentral.gpi.gz

**Comment by cmungall** [comment]
Yep, was waiting on this: https://github.com/RNAcentral/rnacentral-webcode/issues/58#issuecomment-241705349 before pulling in all of RNAC
