### ISSUE TITLE
http://purl.obolibrary.org/obo/go/extensions/go-lego.owl is in manchester syntax

### ISSUE THREAD

**Issue by JervenBolleman** [geneontology/neo#33]
http://purl.obolibrary.org/obo/go/extensions/go-lego.owl
seems to break tools, links and my brain ;)

**Comment by goodb** [comment]
Hi @JervenBolleman .  I had much the same feeling when I started with this project.  It forced me to learn about catalogues in Protege ;).  Could you elaborate slightly more specifically the circumstances leading to your neo-induced brain breakage?  

We've had some ideas about improvements.  Perhaps your use case could help push things over the activation threshold to make some progress on this in coordination with updates to the RDF endpoint.

**Comment by JervenBolleman** [comment]
Hi @goodb the breaking my brain is tongue in cheek. The more important part is that the obolibrary code base doesn't understand Manchester syntax. Giving a big red warning on my firefox browser. Saving the go-lego.owl file in an RDF syntax (probably XML) will allow the obolibrary code to function.

**Comment by cmungall** [comment]
When you say obo library code base which one do you mean? The owl api works
fine but we're should do an rdf serialization so jena rdflib etc can read it

**Comment by JervenBolleman** [comment]
@cmungall please visit the link in my bug report.

**Comment by JervenBolleman** [comment]
@cmungall @goodb is there anything I can do to help?

**Comment by balhoff** [comment]
This file has been in RDF-XML for a while now, so I'll close this.
