### ISSUE TITLE
develop neo-lite for use in go-lego

### ISSUE THREAD

**Issue by goodb** [geneontology/neo#47]
As discussed in Berkeley October 2019, define a new neo build that contains the upper-level classes required to support inferences in Minerva.  

@cmungall fill in details from board...

**Comment by goodb** [comment]
I think this would solve current go_shapes build problem (out of memory) if we did it.  https://travis-ci.com/geneontology/go-shapes/builds/132208210

**Comment by goodb** [comment]
@cmungall could you jot down the plan here?  It isn't crystal clear to me.  If you can help plan it out, I would like to start working on it.  This is getting in the way of everything I am involved with.  See https://github.com/geneontology/go-shapes/pull/167  for the latest.

**Comment by kltm** [comment]
@goodb I'm assuming that this is no longer in the plan?

**Comment by goodb** [comment]
@kltm I don't think so.  My understanding now is that all of the upper level semantics in neo is actually chebi.  I believe we can close this issue.
