### ISSUE TITLE
Create an is-a closure version of NEO for Noctua autocomplete

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/neo#48]
For the ontology autocomplete fields in Noctua it would be good to just use is-a closure.
This would prevent potential confusion about what terms show up in the autocomplete menu and also possible annotation errors.

An example is what currently happens when typing in 'mechano' in the BP field of the form:

![image](https://user-images.githubusercontent.com/1730534/68713890-ce104100-056c-11ea-9ba8-233b64d14613.png)

MF terms are also returned in this search due to the 'part of' relation between some MF and BP terms in the ontology.

See also:
https://github.com/geneontology/noctua-form/issues/34
https://github.com/geneontology/noctua-form/issues/19

**Comment by cmungall** [comment]
This is actually in the solr loading and nothing to do in the solr loader

We actually have a slot in solr for the is-a closure:

https://github.com/geneontology/amigo/blob/99cfac2a8554c0d88fe675c7f0065c04a203ff6a/metadata/ont-config.yaml#L125-L131

And this is being loaded:

https://github.com/geneontology/noctua-form/issues/19#issuecomment-553198688

So I think this issue can be closed?

**Comment by kltm** [comment]
Indeed.
