### ISSUE TITLE
Load GPI file for UniProt reviewed entries for Virus and Bacteria in NEO

### ISSUE THREAD

**Issue by pgaudet** [geneontology/neo#49]
Hello, 

We'd like to load the UniProt reviewed entries for Virus and Bacteria in NEO. 

@alexsign generated a GPI file. 
@kltm Where do we make it available? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Where is this file?

**Comment by pgaudet** [comment]
In my inbox. 

My question was 
> Where do we make it available? 

:) 

Thanks, Pascale

**Comment by kltm** [comment]
Just to follow up on the ticket with conversations help elsewhere:

- [ ] we will be provided a URL for a GPI
- [ ]  we will add this to out metadata
- [ ] we will regenerate the datasets.json used by NEO
- [ ] we will rerun the temporary NEO pipeline
- [ ] we will deploy this new NEO

**Comment by pgaudet** [comment]
This is the URL: ftp://ftp.ebi.ac.uk/pub/contrib/goa/uniprot_reviewed_virus_bacteria.gpi

**Comment by pgaudet** [comment]
@kltm What do we need to do next ? Can we add this to the GOA yaml ?

**Comment by kltm** [comment]
@pgaudet That would be the older file at this point. The way the system works current, the Scov2 stuff is bypassing the main system.

**Comment by cmungall** [comment]
We can go ahead and add this to to neo easily, but there are some things we need to discuss first:

Currently we assume each gpi file is for one species, and we assign a species code. This is for disambiguation of label which is necessary to prevent autocomplete confusion. For example, there are 574 `dnaA` genes here. I suggest we get around this by appending the taxon id to the symbol. It's not perfect but it's simple to implement.

Second, discussing with @pgaudet we decided that we would come up with a GO reference species list and use this instead. Stay tuned.

Third, we will be loading sars-cov-2 twice (this is configured to be loaded from its own gpi, see https://github.com/geneontology/go-site/issues/1431). I think this is what you are referring to Seth?

**Comment by kltm** [comment]
@cmungall I'd have to get it all in my head again to be completely clear, but the current use case for the GPI is for annotation in Noctua: in order to make annotation work we need it in NEO; to get it into NEO, we have the somewhat hacked NEO Makefile with the sars-cov-2 handled as a special case. I was responding to @pgaudet 's query about adding an older file to the main pipeline GOA dataset metadata, which would not support this use case.
