### ISSUE TITLE
NEO no longer seems to build

### ISSUE THREAD

**Issue by kltm** [geneontology/neo#50]
NEO now fails on:
```
12:05:04  gzip -dc mirror/c_elegans.PRJNA13758.current.gene_product_info.gpi.gz | ./gpi2obo.pl -s Cele -n wb > target/neo-wb.obo.tmp && mv target/neo-wb.obo.tmp target/neo-wb.obo
12:05:04  make: *** No rule to make target 'target/neo-gramene_oryza.obo', needed by 'all_obo'.  Stop.
[Pipeline] }
12:05:04  ERROR: script returned exit code 2
```

**Comment by kltm** [comment]
@vanaukenk Would you know where the issue that's being blocked by this is?

**Comment by kltm** [comment]
Also tagging @goodb

**Comment by kltm** [comment]
Natch, likely: https://github.com/geneontology/go-site/commit/4614b3aecf01950dd43a5a1d2ac46853086a37d3

**Comment by kltm** [comment]
@vanaukenk This will complete quite late tonight, so we'll move to test tomorrow. I'd note that quite a few things are different in the metadata, fewer resources as well.

**Comment by goodb** [comment]
I think I'm saying the same thing, but http://geneontology.org/gene-associations/submission/gene_association.gramene_oryza.gz is a 404 and is requested via wget on line 258 of https://github.com/geneontology/neo/blob/763ca74511af8ffbf8242c6c3b0e597ed9e185b6/Makefile-gafs

**Comment by kltm** [comment]
@vanaukenk This has been deployed, with an interesting bump upwards in entities.

**Comment by kltm** [comment]
Now try for https://github.com/geneontology/go-site/issues/1221
