### ISSUE TITLE
Some PR identifiers are not making it into the final (GOlr pipeline) product

### ISSUE THREAD

**Issue by kltm** [geneontology/neo#51]
From @hdrabkin

Newer PRO ids are still not getting into Noctua although they *are* in the GPI file.

Examples: 

* _NOT_ in NEO: PR:000050230, created on 1/30/2020
* _NOT_ in NEO: PR:000050222, created on 11/14/2019

===

* _IN_ NEO: PR:000050061, created 4/1/2019

**Comment by kltm** [comment]
...weird, we just did an update

in the GPI:
```PR      000050230       mAKT2/iso:1/Phos:1      RAC-beta serine/threonine-protein kinase isoform 1 phosphorylated 1 (mouse)             protein taxon:10090     MGI:MGI:104874
```

Change TEST_SRCS = mgi
```
~/local/src/git/neo[master]$:) PATH=/home/sjcarbon/local/src/git/owltools/OWLTools-Runner/bin:$PATH make test_obo
```

**Comment by hdrabkin** [comment]
Sorry; do you mean the two I list are not in the GPI used?

**Comment by kltm** [comment]
@hdrabkin Could you check to see if these are available now?

**Comment by hdrabkin** [comment]
I just checked these two and they are both available in FORM and GRAPH.
Did this use the most recent MGI GPI? I can as Li and Karen to try anything they have recently requested also.

**Comment by krchristie** [comment]
I confirmed that this ID, PR:Q3V365, which was created on 3/10/20, was available in both the Form and the Graph.

**Comment by hdrabkin** [comment]
I have confirmed PR:000050230 is now available (Jan 2020 request)

**Comment by hdrabkin** [comment]
Li just confirmed that a new request  PR:000050231 is now also available in Noctua

**Comment by kltm** [comment]
@hdrabkin Okay, great--we seem to have a building method that is more sensible now.

**Comment by kltm** [comment]
Current problem list from @hdrabkin  
```
PR:000050486
name: alanine--tRNA ligase, cytoplasmic isoform 1 methylated 1 (mouse)

PR:000050487
name: alanine--tRNA ligase, cytoplasmic isoform 1 unmethylated 1 (mouse)
```

**Comment by kltm** [comment]
@hdrabkin These seem to be in the system, albeit under different names:

http://noctua-amigo.berkeleybop.org/amigo/term/PR:000050486
http://noctua-amigo.berkeleybop.org/amigo/term/PR:000050487

They both appear in the dropdown for me.

**Comment by hdrabkin** [comment]
I tried Monday put now they ARE there; Sorry. You can close this. Thanks Seth!

**Comment by kltm** [comment]
@hdrabkin No worries. It is a little odd though. We rolled out (two separate) new release for NEO on Thursday and Friday last week, after a long hiatus due to a conflict upstream. If you were still having issues on Monday, I wonder if something might be getting cached somewhere along the way...
