### ISSUE TITLE
ZFIN genes created in September 2019 and later are not available in Noctua (but available in our GPI)

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/neo#53]
I want to create an annotation to linc.terminator (ZFIN:ZDB-LINCRNAG-190911-1), but this gene is not available in Noctua. I am using the new Noctua form, but the issue is the same in the graph editor. 
1) I am unable to create an annotation using the ID alone - I don't know if this is an expected behavior. 
2) It looks like the new genes created in September 2019 and later are not available in Noctua. 
(examples: ZFIN:ZDB-LINCRNAG-190911-1, ZFIN:ZDB-GENE-190924-2, ZFIN:ZDB-GENE-200114-3). These genes are available in our GPI files. 
This makes me think that there has been a problem with our GPI files since September 2019: 
- either GOC has not been retrieving our latest GPI since September and/or there has been a problem to add the information in Noctua
- or there is a problem with our GPI files and they create an error in GO/Noctua (we have not been notified about such issue, but it is a possibility it is happening). 
Could you please look into this? Thank you

**Comment by kltm** [comment]
Can confirm that it's in NEO:
```
wget http://skyhook.berkeleybop.org/issue-35-neo-test/ontology/neo.obo
grep "ZFIN:ZDB-LINCRNAG-190911-1" neo.obo 
id: ZFIN:ZDB-LINCRNAG-190911-1
xref: ZFIN:ZDB-LINCRNAG-190911-1
```

**Comment by kltm** [comment]
Noting some similarities to #51 and #52

**Comment by kltm** [comment]
Odd:
```
sjcarbon@moiraine:/tmp$:( zgrep -b "ZFIN:ZDB-LINCRNAG-190911-1" golr-index-contents.tgz 
sjcarbon@moiraine:/tmp$:( zgrep -b "ZFIN:ZDB-LINCRNAG-190" golr-index-contents.tgz 
Binary file (standard input) matches
```
It's in NEO, but not making it into Solr. Guesses:
* somehow the Solr load is using a non-local neo
  * that seems right to me--we're possibly loading the "released" neo, not the one we're making here? some import trickery?
* owltools is somehow really screwing things up

**Comment by kltm** [comment]
Déjà vu.

**Comment by kltm** [comment]
I think this is the issue:
https://github.com/geneontology/pipeline/blob/issue-35-neo-test/Jenkinsfile#L53-L65
The "official" neo that we're bringing building the index from is not the one we're making in this pipeline, thus the reason we're so far out of phase.

**Comment by kltm** [comment]
Okay our go-lego.owl is the materialized one, so no help there:
Thus:
http://snapshot.geneontology.org/ontology/extensions/go-lego-edit.ofn
taking us to:
Import(<http://purl.obolibrary.org/obo/go/noctua/neo.owl>)
resolving to 
http://build-artifacts.berkeleybop.org/build-noctua-entity-ontology/latest/neo.owl
which ends in cloudfront...okay, so what is going that then?

**Comment by kltm** [comment]
Well, that's right:
```
sjcarbon@moiraine:/tmp$:) wget http://go-build.s3.amazonaws.com/build-noctua-entity-ontology/latest/neo.owl 
sjcarbon@moiraine:/tmp$:) grep "ZFIN:ZDB-LINCRNAG-190911-1" neo.owl
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ZFIN:ZDB-LINCRNAG-190911-1</oboInOwl:hasDbXref>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ZFIN:ZDB-LINCRNAG-190911-1</oboInOwl:id>
```
Same as  http://build-artifacts.berkeleybop.org/build-noctua-entity-ontology/latest/neo.owl, so the disconnect is elsewhere...

**Comment by kltm** [comment]
Internal-only build matches:
```
sjcarbon@moiraine:/tmp$:( zgrep -b "ZFIN:ZDB-LINCRNAG-190911-1" golr-index-contents.tgz.1 
```
So...that's great, but NEO itself is not the only thing we need--ontology terms, etc.--I essentially need to expose the contents of :
```
Import(<http://purl.obolibrary.org/obo/ro.owl>)
Import(<http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-caro.owl>)
Import(<http://purl.obolibrary.org/obo/go/extensions/legorel.owl>)
Import(<http://purl.obolibrary.org/obo/go/extensions/go-plus.owl>)
Import(<http://purl.obolibrary.org/obo/go/extensions/go-bfo-bridge.owl>)
Import(<http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl>)
Import(<http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim-disjoint-over-in-taxon.owl>)
Import(<http://purl.obolibrary.org/obo/eco/eco-basic.owl>)
Import(<http://purl.obolibrary.org/obo/wbbt.owl>)
Import(<http://purl.obolibrary.org/obo/wbphenotype/wbphenotype-base.owl>)
Import(<http://purl.obolibrary.org/obo/wbphenotype/imports/wbls_import.owl>)
Import(<http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-wbbt.owl>)
Import(<http://purl.obolibrary.org/obo/uberon/bridge/cl-bridge-to-wbbt.owl>)
Import(<http://purl.obolibrary.org/obo/ddanat.owl>)
Import(<http://purl.obolibrary.org/obo/zfa.owl>)
Import(<http://purl.obolibrary.org/obo/emapa.owl>)
Import(<http://purl.obolibrary.org/obo/go/noctua/neo.owl>)
```
except with the last URL the local...or just go ahead and make this job the "official" producer of NEO.

**Comment by goodb** [comment]
@kltm Why don't you build the needed solr index (golr) from the merged go_lego file produced by the ontology build?  e.g. the big monster ontology that you get when you resolve http://purl.obolibrary.org/obo/go/extensions/go-lego.owl

Then you would just have one ontology file to keep track of and we would be closer to having the type-aheads matching the ontologies loaded in minerva.  This would also synchronize the tbox part of the RDF store with everything else.  

Note that there seems to be a problem with that build right now (minimally missing an important subclass relation between protein and information biomacromolecule).  But at least we would have one place to look and work on fixes and tests.  Tagging @balhoff 

Is there some reason, right now, that GOLR needs a different set of terms from Minerva or the RDF store?  (If we do ever successfully escape from having NEO in Minerva we may deal with things differently on the Minerva side but it seems like we need to patch up the existing system first and that everything else here is going to go forward based on the monster merged ontology known as go_lego).

**Comment by kltm** [comment]
@sabrinatoro Could you check to see if these are available now?

**Comment by sabrinatoro** [comment]
@kltm Yes, I am confirming that the genes reported in this tickets are now available in Noctua. Thank you! 
I am closing this ticket (please reopen it if there was more to be done). Thanks!
