### ISSUE TITLE
load curated gpi file for sars-cov-2

### ISSUE THREAD

**Issue by cmungall** [geneontology/neo#60]
We recurated the uniprot goa GPI for sars-cov-2 for another project, we should use this one in Neo
https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/master/curated/ORFs/uniprot_sars-cov-2.gpi

Background:
https://github.com/geneontology/go-site/issues/1431

**Comment by kltm** [comment]
URL: https://raw.githubusercontent.com/Knowledge-Graph-Hub/kg-covid-19/master/curated/ORFs/uniprot_sars-cov-2.gpi
Is this still to replace the currently use URL, or has this moved on?

**Comment by goodb** [comment]
@kltm looking at the line for the protein we've been discussing it looks different from that file.  The label on noctua is showing 'nsp12 Scov2' but here its just 'nsp12'

UniProtKB	P0DTD1-PRO_0000449629	nsp12	RNA-directed RNA polymerase	Pol|RdRp|P0DTD1(4393-5324)|Pol (SARS2)|RdRp (SARS2)|nsp12 (SARS2)|UniProtKB:P0DTD1, 4393-5324|ORF1ab/Clv:nsp12 (SARS2)|Non-structural protein 12|nsp-12|ns12|ns-12|RNA-dependent RNA polymerase|RdRp|Pol|Severe acute respiratory syndrome (SARS) coronavirus nonstructural protein 12|holo-RdRp	protein	taxon:2697049	UniProtKB:P0DTD1	PR:000050284|PRO_0000449629

**Comment by kltm** [comment]
IIRC, the NEO build process adds the species.

**Comment by cmungall** [comment]
Sorry, I let this one slip. The gpi file is good. We should replace the uniprot one with https://raw.githubusercontent.com/Knowledge-Graph-Hub/kg-covid-19/master/curated/ORFs/uniprot_sars-cov-2.gpi

@kltm is correct, the species label is not include in the gpi, it is appended as part of neo generation

**Comment by kltm** [comment]
@cmungall Is this what you are wanting? Is there (ideally?) a better location from the KG-HUB distribution? (https://github.com/geneontology/neo/pull/68)

**Comment by kltm** [comment]
@cmungall I believe this should now be loaded (http://noctua-amigo.berkeleybop.org/amigo/search/ontology)

**Comment by kltm** [comment]
Duped for #85
