### ISSUE TITLE
Is NEO typing PRO identifiers correctly?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/neo#64]
@hdrabkin showed me a model this morning where the ShEx is not validating PRO identifiers as chemical entities, i.e. 'has input' PR:nnnnnnnnnnn, for a MF gives a ShEx validation.

How are PRO identifiers currently typed in neo?

**Comment by deustp01** [comment]
> some are under [amino acid chain](http://purl.obolibrary.org/obo/CHEBI_50047).

That looks like wrong chemistry. CHEBI:50047 "a compound formally derived from ammonia by replacing one, two or three hydrogen atoms by organyl groups" looks like a class of small molecules whose members include, for example, the various amino acid residues found in proteins.

**Comment by vanaukenk** [comment]
@hdrabkin - can you paste the PR ids for the specific examples you showed me?  Thanks!

**Comment by hdrabkin** [comment]
The two in question were actually 'new' (they were the ones that were not in neo for several weeks and then the load was fixed:

[Term]
id: PR:000050486
name: alanine--tRNA ligase, cytoplasmic isoform 1 methylated 1 (mouse)

PR:000050487
name: alanine--tRNA ligase, cytoplasmic isoform 1 unmethylated 1 (mouse)

**Comment by balhoff** [comment]
I think @hdrabkin's comment explains things. I'll close, but let me know if this continues to be a problem.
