### ISSUE TITLE
Tweak obo-uris hack to handle hash injected by OBO parser

### ISSUE THREAD

**Issue by kltm** [geneontology/neo#66]
From @pgaudet 

Patrick pointed out that while the chains are available, their labels don’t show up – only the identifier. Can this be fixed? 

From @balhoff : 

This will be successful if the NEO ontology contains a term with label "nsp4 Scov2" and its IRI looks like `http://identifiers.org/uniprot/P0DTD1-PRO_0000449622` instead of `http://purl.obolibrary.org/obo/UniProtKB#_P0DTD1-PRO_0000449622`.

Also, when this is loaded in Minerva, [this model](http://noctua.geneontology.org/editor/graph/gomodel:5e72450500004237) should no longer have gene products without labels.

**Comment by balhoff** [comment]
This all looks good now.
