### ISSUE TITLE
Check type of mouse ncRNA genes - not recognized in Noctua as valid annotation objects

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/neo#72]
I'm not sure which is the best tracker for this issue, but am starting with NEO.

If a mouse ncRNA gene is used as an enabling entity or an input to a BP or MF, the nodes are being flagged by the ShEx validator because these ncRNA gene identifiers are not recognized as valid annotation objects.

In the MGI gpi file, these genes are typed as ncRNA genes using SO:0001263 according to the [GPI2.0 spec](https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md).

@hdrabkin
@ukemi 
@kltm 
@balhoff 

Note: if I check one of these gene ids, e.g. MGI:2676885, in noctua-amigo, the graph view seems to show the correct parentage.

**Comment by hdrabkin** [comment]
This might be the same issue we had with pro ids (PR:xxxxxxx), also in our gpi. Don't know if THAT was even fixed.

**Comment by balhoff** [comment]
@vanaukenk SO:0001263 does not appear to be in go-lego, so probably the hierarchy isn't connecting.

**Comment by hdrabkin** [comment]
So that would exclude tRNA, miRNA, rRNA, snRNA, snoRNA, lncRNAs as functional gene products yes?

**Comment by balhoff** [comment]
@hdrabkin we do have some of those terms already. It's anything you currently see in the GO editor file.

**Comment by balhoff** [comment]
https://github.com/geneontology/go-ontology/pull/21818

**Comment by vanaukenk** [comment]
Thanks, @balhoff !

**Comment by hdrabkin** [comment]
Using two miRNA genes as input, I verify that now no more 'red dots' from ShEx. 
Thanky @balhoff !
