### ISSUE TITLE
Would like phage proteins to be available

### ISSUE THREAD

**Issue by dsiegele** [geneontology/neo#94]
Q1) I tried to create models for some phage pathways, but found very few phage proteins available in the Visual Pathway Editor. I was entering reviewed UniProt identifers. There were a few proteins from phages Qbeta and MS2, but apparently none for:
-Escherichia phage Lambda (Taxon 10710; 88 reviewed proteins)
-Enterobacteria phage T4 (Taxon 10665; 268 reviewed proteins)
-Enterobacteria phage N4 (Taxon 10752; 72 reviewed proteins)
-Escherichia phage P1 (Taxon 10678; 33 reviewed proteins)

Q2) Some of the phage proteins haven't been reviewed by UniProt. For those cases, can I request that a particular set of proteins be loaded?

Thank you!

**Comment by pgaudet** [comment]
Hi @dsiegele 

Do you have specific examples of reviewed UniProt entries that you cannot use? The entries I tested for some of these species worked.

Thanks, Pascale

**Comment by pgaudet** [comment]
@dsiegele we have found a bug in the load, and have now loaded more entities. Please reopen if you still see issues with the proteins you want to annotate.

Thanks, Pascale
